version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      # アクセスログ・エラーログを外部に保存する
      - ./logs/nginx:/var/log/nginx
      # 設定ファイルを外部に保存する
      - ./nginx/conf.d:/etc/nginx/conf.d
      # Laravelプロジェクトと繋ぐ
      - ./src:/var/www/src
    ports:
      - 58710:80
    networks:
      - akipon_app_network
    depends_on:
      # PHPの後に処理を実行しはじめる
      - phpfpm
    tty: true

  phpfpm:
    build:
      context: .
      dockerfile: ./phpfpm/Dockerfile
    volumes:
      - ./src:/var/www/src
    networks:
      - akipon_app_network
    depends_on:
      - mysql
    tty: true

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    volumes: 
      - ./logs/mysql:/var/log/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d/
      # - ./mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - 58720:3306
    networks:
      - akipon_app_network
    tty: true

networks:
  akipon_app_network:
